const productsList = [
    {_id:1,
      title: `7UP - 2000ml`,
      imgLink: `https://api.redgrocer.com/api/upload/images/7up-1000-ml-5fa9.jpg`,
      newPrice: 130,
      oldPrice: 120,
      discount: 401,
    },
    {_id:2,
      title: `Coca-Cola Soft Drinks - 1.25ltr`,
      imgLink: `https://api.redgrocer.com/api/upload/images/coca-cola-soft-drinks-1ltr-df30.jpg`,
      oldPrice: 1600,
      newPrice: 1200,
      discount: 400,
    },
    {
      _id:3,
      title: `Cerelac Rice, Potato &amp; Chicken - (12 - 24
        Months) - 350gm`,
      imgLink: `https://api.redgrocer.com/api/upload/images/cerelac-rice-potato-chicken-12-24-months-350gm-4e9c.jpg`,
      oldPrice: 3099,
      newPrice: 2799,
      discount: 300,
    },
    {
      _id:4,
      title: `Cerelac Wheat With Milk (6-24 Month) - 400gm`,
      imgLink: `https://api.redgrocer.com/api/upload/images/cerelac-wheat-with-milk-6-24-month-400gm-3eb5.jpg`,
      oldPrice: 3099,
      newPrice: 2799,
      discount: 300,
    },
    {
      _id:5,
      title: `Local Garlic / Deshi Rashun 500gm`,
      imgLink: `https://api.redgrocer.com/api/upload/images/garlic-local-deshi-rashun-e105b.jpeg`,
      oldPrice: 3099,
      newPrice: 2799,
      discount: 300,
    },
    {
      _id:6,
      title: `Chao Chao lollipop- 30pcs`,
      imgLink: `https://api.redgrocer.com/api/upload/images/chao-chao-lollipop-1pcs-1a22.jpg`,
      oldPrice: 3099,
      newPrice: 2799,
      discount: 300,
    },
    {
      _id:7,
      title: `NutCandy Wasabi Coated Green Peas (Spicy Hot) -
      180gm`,
      imgLink: `https://api.redgrocer.com/api/upload/images/nutcandy-wasabi-coated-green-peas-spicy-hot-180gm-25e2.jpg`,
      oldPrice: 3099,
      newPrice: 2799,
      discount: 300,
    },
    {
      _id:8,
      title: `Kishwan Sweet Toast - 250gm`,
      imgLink: `https://api.redgrocer.com/api/upload/images/kishwan-sweet-toast-250gm-37ca.jpg`,
      oldPrice: 3099,
      newPrice: 2799,
      discount: 300,
    },
    {
      _id:9,
      title: `Well Food Coconut Toast Biscuit - 200gm`,
      imgLink: `https://api.redgrocer.com/api/upload/images/well-food-coconut-toast-biscuit-200gm-d486.jpg`,
      oldPrice: 3099,
      newPrice: 2799,
      discount: 300,
    },
    {
      _id:10,
      title: `Well Food Laccha Semai 200gm`,
      imgLink: `https://api.redgrocer.com/api/upload/images/well-food-laccha-semai-400-gm-1fe1.jpg`,
      oldPrice: 3099,
      newPrice: 2799,
      discount: 300,
    }
  ];

  export default productsList;
